name: 🤖 dep auto merge

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  pull-requests: write
  issues: write
  repository-projects: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: khulnasoft-lab/dependabot-auto-merge@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          target: all
