name: Ingest Cloud OSV

on:
  schedule:
    - cron: '0 * * * *' # Every hour
  workflow_dispatch:

permissions: read-all

jobs:
  ingest-osv:
    name: Ingest Cloud OSV
    continue-on-error: false
    runs-on: ubuntu-latest
    timeout-minutes: 45 # Don't allow the job to run too long.

    permissions:
      actions: read
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.ORG_REPO_TOKEN }}
        
    - uses: actions/setup-go@v5.0.1
      with:
        go-version: "1.21"

    - name: GCP Credential Workaround
      run: |
        echo '{ "type": "service_account" }' > .dummy_adc.json

    - name: Ingest OSV
      run: |
        go run ./cmd/ingest -config config/config.yaml -start-keys config/start-keys.yaml
      env:
        GOOGLE_APPLICATION_CREDENTIALS: .dummy_adc.json

    - name: Prepare commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add osv config/start-keys.yaml

    - name: Commit report changes
      run: git diff --cached --quiet || git commit -m 'Ingest OSV - Cloud Storage'

    - name: Push commit
      run: git push
